FROM python:3.11-slim

ARG SSH_PRIVATE_KEY
ARG GIT_BRANCH

RUN apt-get update && \
    apt-get install -y openssh-client && \
    apt-get install -y git && \
    mkdir -p /root/.ssh && \
    echo "${SSH_PRIVATE_KEY}" > /root/.ssh/id_rsa && \
    chmod 600 /root/.ssh/id_rsa && \
    ssh-keyscan -t rsa github.com >> /root/.ssh/known_hosts

RUN git clone git@github.com:Helmholtz-AI-Energy/assas_database.git /app
WORKDIR /app
RUN git fetch origin && \
    git checkout ${GIT_BRANCH} && \
    git reset --hard origin/${GIT_BRANCH} && \
    echo "Checked out remote branch ${GIT_BRANCH}"

RUN pip install --no-cache-dir -r requirements.txt

