FROM python:3.11-slim

ENV ASTEC_ROOT=/opt/astec_installer

ARG SSH_PRIVATE_KEY
ARG LSDF_USER
ARG LSDF_PWD
ARG GIT_BRANCH

RUN apt-get update && \
    apt-get install -y openssh-client && \
    apt-get install -y git && \
    mkdir -p /root/.ssh && \
    echo "${SSH_PRIVATE_KEY}" > /root/.ssh/id_rsa && \
    chmod 600 /root/.ssh/id_rsa && \
    ssh-keyscan -t rsa github.com >> /root/.ssh/known_hosts

WORKDIR /app

RUN git clone git@github.com:Helmholtz-AI-Energy/assas_database.git /app
RUN git fetch origin && \
    git checkout ${GIT_BRANCH} && \
    git reset --hard origin/${GIT_BRANCH} && \
    echo "Checked out remote branch ${GIT_BRANCH}"

RUN mkdir -p ${ASTEC_ROOT}
RUN apt-get update && apt-get install -y sshpass
RUN sshpass -p "${LSDF_PWD}" scp -r -o StrictHostKeyChecking=no ${LSDF_USER}@os-login.lsdf.kit.edu:/lsdf/kit/scc/projects/ASSAS/tmp/astec_installer/astecV3.1.2_linux64.tgz ${ASTEC_ROOT}
RUN ls -l ${ASTEC_ROOT}

RUN pip3 install --no-cache-dir -r requirements.txt
RUN pip3 install -e .
RUN pip3 list

RUN apt-get update && apt-get install -y csh

RUN tar -xzf $ASTEC_ROOT/astecV3.1.2_linux64.tgz -C $ASTEC_ROOT 
RUN ls -l $ASTEC_ROOT
RUN ls -l $ASTEC_ROOT/astecV3.1.2_linux64
RUN ls -l $ASTEC_ROOT/astecV3.1.2_linux64/astecV3.1.2-install-linux
RUN file $ASTEC_ROOT/astecV3.1.2_linux64/astecV3.1.2-install-linux
RUN chmod +x $ASTEC_ROOT/astecV3.1.2_linux64/astecV3.1.2-install-linux
RUN csh $ASTEC_ROOT/astecV3.1.2_linux64/astecV3.1.2-install-linux