"""Generate DataCite JSON metadata files for datasets in the ASSAS database."""

import os
import json
import h5py
from datetime import date
from assasdb import AssasDatabaseManager, AssasDatabaseHandler, AssasDocumentFileStatus


def generate_datacite_json(entry: dict, output_dir: str) -> str:
    """Generate a DataCite JSON metadata file for a given database entry.

    Args:
        entry (dict): A dictionary containing metadata about the dataset.
        output_dir (str): Directory where the JSON file will be saved.

    Returns:
        str: Path to the generated JSON file.

    """
    file_path = entry["system_path"]
    dataset_title = (
        f"ASTEC Simulation Dataset - "
        f"{entry.get('system_name', os.path.basename(file_path))}"
    )
    creator = "ASSAS Project, KIT SCC"
    publisher = "Karlsruhe Institute of Technology (KIT)"
    version = "1.0"
    license_str = "CC-BY 4.0"
    description = entry.get(
        "meta_description",
        "Simulation dataset generated by ASTEC and managed by ASSAS.",
    )
    keywords = entry.get(
        "meta_keywords", ["ASTEC", "simulation", "nuclear safety", "ASSAS"]
    )
    landing_page = entry.get("meta_landing_page", "https://datahub.assas.kit.edu/")
    funding_reference = entry.get(
        "meta_funding",
        "BMBF Project ASSAS - FAIR Surrogate Modelling for Nuclear Safety Data",
    )
    file_size_gb = (
        os.path.getsize(file_path) / (1024**3) if os.path.exists(file_path) else 0
    )

    attrs = {}
    try:
        with h5py.File(file_path, "r") as f:
            for key, val in f.attrs.items():
                attrs[key] = str(val)
    except Exception:
        pass

    metadata = {
        "types": {"resourceTypeGeneral": "Dataset", "resourceType": "HDF5 file"},
        "creators": [{"name": creator}],
        "titles": [{"title": dataset_title}],
        "publisher": publisher,
        "publicationYear": date.today().year,
        "subjects": [{"subject": k} for k in keywords],
        "contributors": [
            {"name": "IRSN", "contributorType": "ResearchGroup"},
            {"name": "SCC KIT", "contributorType": "DataCurator"},
        ],
        "language": "en",
        "version": version,
        "descriptions": [{"descriptionType": "Abstract", "description": description}],
        "rightsList": [{"rights": license_str}],
        "sizes": [f"{file_size_gb:.2f} GB"],
        "formats": ["HDF5"],
        "fundingReferences": [{"funderName": funding_reference}],
        "relatedIdentifiers": [],
        "identifier": {
            "identifierType": "DOI",
            "identifier": entry.get(
                "meta_doi", f"10.35097/assas.{entry.get('system_name', 'unknown')}.v1"
            ),
        },
        "url": landing_page,
        "alternateIdentifiers": [
            {
                "alternateIdentifierType": "FileName",
                "alternateIdentifier": os.path.basename(file_path),
            }
        ],
        "schemaVersion": "http://datacite.org/schema/kernel-4",
    }

    if attrs:
        metadata["descriptions"].append(
            {
                "descriptionType": "TechnicalInfo",
                "description": json.dumps(attrs, indent=2),
            }
        )

    out_name = f"{entry.get('system_name', os.path.basename(file_path))}_datacite.json"
    out_path = os.path.join(output_dir, out_name)

    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(metadata, f, indent=2)

    return out_path


if __name__ == "__main__":
    database_handler = AssasDatabaseHandler(client=None)
    database_manager = AssasDatabaseManager(database_handler=database_handler)
    dataframe = database_manager.get_all_database_entries_from_backup()

    output_dir = "datacite_jsons"
    os.makedirs(output_dir, exist_ok=True)

    for idx, entry in dataframe.iterrows():
        try:
            if entry["system_status"] != AssasDocumentFileStatus.VALID.value:
                continue
            out_path = generate_datacite_json(entry, output_dir)
            print(f"Generated DataCite JSON: {out_path}")
        except Exception as e:
            print(f"Error for entry {entry.get('system_name', idx)}: {e}")
